### ISSUE TITLE
Comparison of SCL files to find differences

### ISSUE THREAD

**Issue by MohKum00** [openscd/openscd.github.io#1]
While working on the same project sometimes it is required to check/compare a new .scd(SCL) file to older one to understand the changes... This helps in keeping a track of changes made during engineering process.

**Comment by JakobVogelsang** [comment]
Hi Mohit, I am very sorry I just saw this issue. Please submit your issues to [open-scd](https://www.github.com/openscd/open-scd). This repo is the one we are using to deploy OpenSCD on openscd.github.io
